services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ts2
      POSTGRES_PASSWORD: "Fj-7AiUqLX6c5rnwV9afvOddZmIIzIE1"
    volumes:
      - ts2_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "n44PE4Gwyxi1kbW_Y-OiWEp_wkVDbud3"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ts2_test
      POSTGRES_PASSWORD: "cYi9Dy8ZArwSW6ZSLOE2ri70124ZLxY0"
    volumes:
      - ts2_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "17QxOztlE8n10vs8oTm8FNPMdkdnWhQX"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  ts2_data:
  ts2_test_data:
