name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ master ] # Срабатывает при пуше в ветку main
  workflow_dispatch:      # Позволяет запускать вручную из интерфейса GitHub

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create or Update Kubernetes Secret
        run: |
          kubectl create secret generic serverpod-secrets-ts2 \
            --from-literal=database-password='${{ secrets.DB_PASSWORD }}' \
            --from-literal=redis-password='${{ secrets.REDIS_PASSWORD }}' \
            --from-literal=service-secret='${{ secrets.SERVICE_SECRET }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Log in to Timeweb Container Registry
        uses: docker/login-action@v3
        with:
          registry: dbe81550-wise-chickadee.registry.twcstorage.ru
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ts2_server # Указываем контекст для сборки
          file: ./ts2_server/Dockerfile.prod # Путь к вашему Dockerfile
          push: true
          tags: dbe81550-wise-chickadee.registry.twcstorage.ru/ts2-server:latest

  deploy-to-cluster:
    needs: build-and-push-image # Эта задача начнется только после успешной сборки и пуша образа
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Kubernetes manifests
        run: |
          # Применяем все конфигурации из папки k8s
          kubectl apply -f ts2_server/k8s/
          
          # Принудительно перезапускаем Deployment, чтобы он точно подхватил новый образ
          kubectl rollout restart deployment ts2-server-deployment